### PR TITLE
Fixed stack popping issue.

### PR DESCRIPTION
**Pull request by rayguan97**

### CODE REVIEW

**Comment by rayguan97** [comment]
testing

**Comment by JasonFil** [comment]
Dear rayguan97, just for your own benefit (even though I think you have understood what's going on): what you have been trying to do here is a so-called "pull request": that is to say, you are asking me to merge your changes to mine, to the branch that all students pull from. That's not what you want to do: what you want to do is `clone` the repo locally, in your hard drive, and then try the commands in your own machine. I actually think you did a `git push` here, which if I remember is part of the homework. If you did this, it's very natural that I saw a pull request here; I will just have to deny any PR that comes my way. You're good on any count; I just wanted to make sure you know what you're doing.

**Comment by rayguan97** [comment]
Sorry about the inconvenience! I actually forked your directory and tried to push local changes to my github, but I accidentally pushed to yours and PR, which I thought was my github. Thanks for your understanding tho!!!

**Comment by JasonFil** [comment]
So, for my own understanding, how does forking work with the local remotes? That is to say, did you have to fork, then clone from your own account, and then push any local changes? What was the remote that you fed to `git push`?

**Comment by rayguan97** [comment]
Since I was reading from tutorials, I started cloning from your directory. Then I realized I should fork your work to my account to not affect my classmates. Then I added a remote of my own directory to local. I thought I push twice. Once I realized it was a mistake to push to yours, I pushed to mine again. I mean thanks for the understanding of the mistake!

**Pull request closed without merging**
